[package]
name = "disc_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.5"
serenity-voice-model = "0.1.1"
songbird = "0.3.2"
tokio = { version = "1", features = ["full"] }
